baseurl = "https://mtik00.com"
languageCode = "en-us"
title = "mtik00"
publishdir = "../build"
disqusShortname = "mtik00"
theme = "hugo-redlounge"
pygmentsstyle = "friendly"

[taxonomies]
    post = "posts"
    category = "categories"
    archive = "archives"

[params]
    Copyright = "<a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/' target='_blank'><img alt='Creative Commons License' style='border-width:0' src='https://licensebuttons.net/l/by-nc-sa/4.0/88x31.png' /></a><br /><span xmlns:dct='http://purl.org/dc/terms/' property='dct:title'>mtik00.com</span> by <a xmlns:cc='http://creativecommons.org/ns#' href='http://mtik00.com' property='cc:attributionName' rel='cc:attributionURL' target='_blank'>Timothy McFadden</a> is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/' target='_blank'>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."
    sidebartitle = "mtik00"
    sidebartagline = "Musings on software"
    socialsharing = true
    gaid = "UA-4067506-4"

    # lunr search parameters
    lunr = true

    # cache-busting urls.  Set this to "?...." to change all of the URLs for
    # the static content.
    static_version = "?v2"

[permalinks]
    posts = "/:year/:month/:slug/"

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 100

[[menu.main]]
    name = "Archives"
    url = "/archives"
    weight = 300

[[menu.social]]
    pre = "<i class='fa fa-github fa-lg'></i>"
    url = "https://github.com/mtik00"
    identifier = "github"
    weight = -900

[[menu.social]]
    pre = "<i class='fa fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/timothymcfadden"
    identifier = "linkedin"
    weight = -200

[[menu.social]]
    pre = "<i class='fa fa-stack-overflow fa-lg'></i>"
    url = "http://stackoverflow.com/users/3696827/mtik00"
    weight = -400

[[menu.social]]
    pre = "<i class='fa fa-rss fa-lg'></i>"
    url = "http://feeds.feedburner.com/mtik00"
    identifier = "rss"
    weight = -100